import{a as L,S as v,i as d}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const E="https://pixabay.com/api/",w="46219346-243694830f7cca451bf7f7da0",u=15;async function m(a,t=1){const o=new URLSearchParams({q:a,per_page:u,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t}),i=`${E}?key=${w}&${o}`,e=await L.get(i);if(e.data.hits.length===0){const s="Не знайшлося відповідного контенту, спробуйте знову";throw new Error(s)}return e.data}document.querySelector(".gallery");function p(a){const t=a.hits.map(({webformatURL:o,largeImageURL:i,tags:e,likes:s,views:n,comments:g,downloads:y})=>`
            <li class="gallery-item">
                <a href="${i}" class="gallery-link">
                    <img src="${o}" alt="${e}" class="gallery-image" />
                </a>
                <div class="info">
                    <p class="info-item"><span>Likes</span> ${s}</p>
                    <p class="info-item"><span>Views</span> ${n}</p>
                    <p class="info-item"><span>Comments</span> ${g}</p>
                    <p class="info-item"><span>Downloads</span> ${y}</p>
                </div>
            </li>
        `).join("");r.list.insertAdjacentHTML("beforeend",t)}const r={form:document.querySelector(".form"),loader:document.querySelector(".loader"),list:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn")};r.form.addEventListener("submit",b);r.loadMoreBtn.addEventListener("click",M);let h=new v(".gallery a"),l=1,c=null,f=0;async function M(a){l+=1;try{const t=await m(c,l);f=t.totalHits/u,(t.hits.length===0||l>f)&&(r.loadMoreBtn.classList.add("is-hidden"),setTimeout(()=>{d.error({position:"topRight",message:"Вибачте, але ви досягли кінця результатів пошуку."})},1e3)),p(t),h.refresh(),B()}catch(t){console.log(t)}}async function b(a){a.preventDefault();const t=a.currentTarget;if(l=1,r.list.innerHTML="",c=a.target.elements["search-area"].value.trim(),c===""){d.error({position:"topRight",message:"Введіть будь-ласка значення для пошуку"});return}r.loader.classList.add("active");try{const o=await m(c);f=o.totalHits/u,p(o),r.loader.classList.remove("active"),h.refresh(),o.hits.length<15||o.hits.length===0?r.loadMoreBtn.classList.add("is-hidden"):r.loadMoreBtn.classList.remove("is-hidden")}catch(o){r.loader.classList.remove("active"),r.loadMoreBtn.classList.add("is-hidden"),r.list.innerHTML="",d.error({position:"topRight",message:o.message})}finally{t.reset()}}function B(){const t=r.list.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
