import{a as L,S as v,i as d}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const E="https://pixabay.com/api/",M="46219346-243694830f7cca451bf7f7da0",f=15;async function u(a,t=1){const o=new URLSearchParams({q:a,per_page:f,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t}),i=`${E}?key=${M}&${o}`,e=await L.get(i);if(e.data.hits.length===0){const r="Не знайшлося відповідного контенту, спробуйте знову";throw new Error(r)}return e.data}document.querySelector(".gallery");function m(a){const t=a.hits.map(({webformatURL:o,largeImageURL:i,tags:e,likes:r,views:n,comments:g,downloads:y})=>`
            <li class="gallery-item">
                <a href="${i}" class="gallery-link">
                    <img src="${o}" alt="${e}" class="gallery-image" />
                </a>
                <div class="info">
                    <p class="info-item"><span>Likes</span> ${r}</p>
                    <p class="info-item"><span>Views</span> ${n}</p>
                    <p class="info-item"><span>Comments</span> ${g}</p>
                    <p class="info-item"><span>Downloads</span> ${y}</p>
                </div>
            </li>
        `).join("");s.list.insertAdjacentHTML("beforeend",t)}const s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),list:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn")};s.form.addEventListener("submit",b);s.loadMoreBtn.addEventListener("click",w);let p=new v(".gallery a"),c=1,l=null,h=0;async function w(a){c+=1;try{const t=await u(l,c);if(m(t),p.refresh(),B(),c>Math.min(h,33)){s.loadMoreBtn.classList.add("is-hidden"),d.error({position:"topRight",message:"Вибачте, але ви досягли кінця результатів пошуку."});return}}catch(t){console.log(t)}}async function b(a){a.preventDefault();const t=a.currentTarget;if(s.list.innerHTML="",l=a.target.elements["search-area"].value.trim(),l===""){d.error({position:"topRight",message:"Введіть будь-ласка значення для пошуку"});return}s.loader.classList.add("active");try{const o=await u(l);h=Math.ceil(o.totalHits/f),m(o),s.loader.classList.remove("active"),p.refresh(),o.hits.length<15?s.loadMoreBtn.classList.add("is-hidden"):s.loadMoreBtn.classList.remove("is-hidden")}catch(o){s.loader.classList.remove("active"),s.loadMoreBtn.classList.add("is-hidden"),s.list.innerHTML="",d.error({position:"topRight",message:o.message})}finally{t.reset()}}function B(){const t=s.list.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
