import{a as L,S as v,i as d}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const E="https://pixabay.com/api/",M="46219346-243694830f7cca451bf7f7da0",m=15;async function p(i,t=1){if(i===""){iziToast.error({position:"topRight",message:"Введіть будь-ласка значення для пошуку"});return}const o=new URLSearchParams({q:i,per_page:m,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t}),a=`${E}?key=${M}&${o}`,e=await L.get(a);if(e.data.hits.length===0){const s="Не знайшлося відповідного контенту, спробуйте знову";throw new Error(s)}return e.data}document.querySelector(".gallery");function u(i){const t=i.hits.map(({webformatURL:o,largeImageURL:a,tags:e,likes:s,views:n,comments:g,downloads:y})=>`
            <li class="gallery-item">
                <a href="${a}" class="gallery-link">
                    <img src="${o}" alt="${e}" class="gallery-image" />
                </a>
                <div class="info">
                    <p class="info-item"><span>Likes</span> ${s}</p>
                    <p class="info-item"><span>Views</span> ${n}</p>
                    <p class="info-item"><span>Comments</span> ${g}</p>
                    <p class="info-item"><span>Downloads</span> ${y}</p>
                </div>
            </li>
        `).join("");r.list.insertAdjacentHTML("beforeend",t)}const r={form:document.querySelector(".form"),loader:document.querySelector(".loader"),list:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn")};r.form.addEventListener("submit",B);r.loadMoreBtn.addEventListener("click",w);let h=new v(".gallery a"),l=1,c=null,f=0;async function w(i){l+=1;try{const t=await p(c,l);f=t.totalHits/m,(t.hits.length===0||l>f)&&(r.loadMoreBtn.classList.add("is-hidden"),setTimeout(()=>{d.error({position:"topRight",message:"Вибачте, але ви досягли кінця результатів пошуку."})},1e3)),u(t),h.refresh(),$()}catch(t){console.log(t)}}async function B(i){i.preventDefault();const t=i.currentTarget;if(r.loadMoreBtn.classList.add("is-hidden"),l=1,r.list.innerHTML="",c=i.target.elements["search-area"].value.trim(),c===""){d.error({position:"topRight",message:"Введіть будь-ласка значення для пошуку"});return}r.loader.classList.add("active");try{const o=await p(c,l);f=o.totalHits/m,u(o),r.loader.classList.remove("active"),h.refresh(),o.hits.length<15||o.hits.length===0?r.loadMoreBtn.classList.add("is-hidden"):r.loadMoreBtn.classList.remove("is-hidden")}catch(o){r.loader.classList.remove("active"),r.loadMoreBtn.classList.add("is-hidden"),r.list.innerHTML="",d.error({position:"topRight",message:o.message})}finally{t.reset()}}function $(){const t=r.list.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
